<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="paginaBorrar.aspx.cs" Inherits="UltimoEjercicio.View.paginaBorrar" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:GridView ID="GridView1" runat="server" OnRowDataBound="GridView1_RowDataBound" AutoGenerateDeleteButton="True" OnRowDeleting="GridView1_RowDelete">
            </asp:GridView>
        </div>
        <asp:Button ID="btnVolver" runat="server" OnClick="btnVolver_Click" Text="Volver" />
    </form>
</body>
</html>
